language: go
go:
  - 1.13.x
before_install:
  - openssl aes-256-cbc -K $encrypted_d80a2d296111_key -iv $encrypted_d80a2d296111_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
deploy:
  provider: gae
  keyfile: "client-secret.json"
  project: "covid-india-19"