language: go
go:
- 1.13.x
deploy:
  provider: gae
  keyfile: client-secret.json
  project: covid-india-19
before_install:
- openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
  -in client-secret.json.enc -out client-secret.json -d
